/********************************************************
*														*
*			  University of Stunting 2018			    *
*		Build: 1	Version 1.0		Server: 0.3.7		*
*												   		*
*	- Developer: XeonTM									*
* 	- File: Admins Functions file.					   	*
*														*
*********************************************************/

AdminLevel(playerid, level)
{
	if(level >= PlayerInfo[playerid][Admin])
}

HelperLevel(playerid, level)
{

}

GetAdminLevelName(level)
{

}

GetHelperLevelName(level)
{
	
}

GetListofAdmins(level)
{
	
}

GetListofHelper(level)
{
	
}

ConnectedAdmins()
{

}

ConnectedHelpers()
{

}