/********************************************************
*														*
*			  University of Stunting 2018			    *
*		Build: 1	Version 1.0		Server: 0.3.7		*
*												   		*
*	- Developer: XeonTM									*
* 	- File: Hunting games file.					   		*
*														*
*********************************************************/

public MoneyBag()
{
	
}

public GiftsHunt()
{

}

public CookiesHunt()
{

}