/********************************************************
*														*
*			  University of Stunting 2018			    *
*		Build: 1	Version 1.0		Server: 0.3.7		*
*												   		*
*	- Developer: XeonTM									*
* 	- File: Configuration file.							*
*														*
*********************************************************/


// MySQL Settings
#define MYSQL_HOST	    ""
#define MYSQL_USER	    ""
#define MYSQL_PASSWORD  ""	
#define MYSQL_DATABASE  ""

// Hostnames.

#define HOSTNAME_1 		"UoS >> .::University of Stunting::. << UoS"
#define HOSTNAME_2		"UoS >> Freeroam/Stunt/Fornite/DM/Parkour/Hunts"
#define HOSTNAME_3		"UoS >> First Fortnite Server in samp. << UoS"
#define HOSTNAME_4		"UoS >> We are back! with much more features << UoS"

// General Settings
#define SERVER_NAME     "University of Stunting"
#define SERVER_TAG 	    "UoS"
#define SERVER_MODE     ".:Freeroam/DM/Stunt/Race:."

// Management Bot.
#define IRC_BOT_NAME    "Steven"
#define IRC_BOT_ALT     "Uos_Steven"
#define IRC_BOT_PASS    "Uosstevnlegend"
#define IRC_BOT_MAIL    "sometmpemail@tempemail.tempdomain"

// Echo IRC Bots.
#define IRC_BOT_PREFIX  "UoS_%d"
#define IRC_BOT_APREFIX "UoSLegend_%d"
#define IRC_BOT_UPREFIX "UoSBot_%d"

#define IRC_SERVER 		" "
#define IRC_PORT 		" "

// Discord Roles.
#define STAFF_ROLE  	" "
#define HELPER_ROLE 	" "
#define VIP_ROLE		" "


