CREATE TABLE IF NOT EXISTS `Bans`(
	(
		ID INT NOT NULL AUTO_INCREMENT,
		Name VARCHAR(24),
		IP VARCHAR(16), 
		GPCI VARCHAR(50), 
		Reason VARCHAR(50), 
		Admin VARCHAR(24), 
		BanDate VARCHAR(24), 
		Days INT NOT NULL DEFAULT VALUE '-1'
	);

CREATE TABLE IF NOT EXISTS `Kicks`(
	(
		ID INT NOT NULL AUTO_INCREMENT,
		Name VARCHAR(24),
		IP VARCHAR(16), 
		GPCI VARCHAR(50), 
		Reason VARCHAR(50), 
		Admin VARCHAR(24), 
		KickDate VARCHAR(24) 
	);